name := "ClabeValidatorProject"
version := "1.0"
scalaVersion := "2.13.8"
libraryDependencies += "org.scalactic" %% "scalactic" % "3.2.18"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.18" % "test"
resolvers += "Artima Maven Repository" at "https://repo.artima.com/releases"